# SwiftLint Configuration for osmo

# Paths to include
included:
  - osmo

# Paths to exclude
excluded:
  - osmo/Assets.xcassets
  - osmo.xcodeproj
  - osmoTests
  - osmoUITests

# Rules
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

disabled_rules:
  - trailing_whitespace
  - line_length
  - file_length
  - type_body_length
  - function_body_length

# Rule configurations
identifier_name:
  min_length: 2
  max_length: 50
  
type_name:
  min_length: 3
  max_length: 50

# Custom rules
custom_rules:
  no_print_statements:
    regex: 'print\('
    message: "Use logger instead of print statements"
    severity: warning
    
  no_uikit_imports:
    regex: '^import UIKit$'
    message: "Use SwiftUI instead of UIKit"
    severity: error